# Generated by Django 4.2.1 on 2023-05-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("t_name", models.CharField(max_length=15)),
                ("gender", models.CharField(max_length=2)),
                (
                    "t_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("qualifications", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=10)),
                ("year", models.DateField()),
            ],
        ),
    ]
