# Generated by Django 4.2.1 on 2023-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depid", models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(model_name="teacher", old_name="t_id", new_name="tid",),
        migrations.RenameField(
            model_name="teacher", old_name="t_name", new_name="tname",
        ),
    ]
