# Generated by Django 4.2.1 on 2023-05-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_department_rename_t_id_teacher_tid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subid", models.CharField(max_length=15)),
                ("subname", models.CharField(max_length=15)),
                ("sem", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(name="Department",),
        migrations.AddField(
            model_name="teacher",
            name="tmail",
            field=models.CharField(default=None, max_length=15),
        ),
    ]
