# Generated by Django 4.2.1 on 2023-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_subject_delete_department_teacher_tmail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "depid",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("depname", models.CharField(default=None, max_length=10)),
            ],
        ),
    ]
