# Generated by Django 4.2.1 on 2023-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_department"),
    ]

    operations = [
        migrations.RemoveField(model_name="subject", name="id",),
        migrations.AlterField(
            model_name="subject",
            name="subid",
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
