# Generated by Django 4.2.1 on 2023-05-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_remove_subject_id_alter_subject_subid"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="HODnanme",
            field=models.CharField(default=None, max_length=15),
        ),
    ]
