# Generated by Django 4.2.1 on 2023-06-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_department_hodnanme"),
    ]

    operations = [
        migrations.DeleteModel(name="Department",),
    ]
