# Generated by Django 4.2.1 on 2023-06-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_delete_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "depid",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("depname", models.CharField(default=None, max_length=10)),
                ("HODnanme", models.CharField(default=None, max_length=15)),
            ],
        ),
    ]
