# Generated by Django 4.2.1 on 2023-06-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_department"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department", old_name="HODnanme", new_name="HODname",
        ),
    ]
