# Generated by Django 4.2.1 on 2023-06-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_rename_hodnanme_department_hodname"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="depid",
            field=models.ForeignKey(
                default="D0001",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.department",
            ),
        ),
    ]
