# Generated by Django 4.2.1 on 2023-06-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_teacher_depid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher", name="gender", field=models.CharField(max_length=10),
        ),
    ]
