# Generated by Django 4.2.1 on 2023-06-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_teacher_gender"),
    ]

    operations = [
        migrations.RemoveField(model_name="teacher", name="qualifications",),
        migrations.AlterField(
            model_name="department",
            name="HODname",
            field=models.CharField(default=None, max_length=25),
        ),
    ]
