# Generated by Django 4.2.1 on 2023-06-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_remove_teacher_qualifications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="tmail",
            field=models.CharField(default=None, max_length=35),
        ),
    ]
