# Generated by Django 4.2.1 on 2023-06-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_subject_depid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subid",
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
