# Generated by Django 4.2.1 on 2023-06-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_login"),
    ]

    operations = [
        migrations.RenameField(
            model_name="login", old_name="password", new_name="pass1",
        ),
    ]
