# Generated by Django 4.2.1 on 2023-06-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_rename_password_login_pass1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="login", old_name="pass1", new_name="password",
        ),
    ]
