# Generated by Django 4.2.1 on 2023-06-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_rename_pass1_login_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="year",
            field=models.CharField(default="2022", max_length=10),
        ),
        migrations.AddField(
            model_name="teacher",
            name="pos",
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
