# Generated by Django 4.2.1 on 2023-06-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_subject_year_teacher_pos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher", name="pos", field=models.IntegerField(default=0),
        ),
    ]
