# Generated by Django 4.2.1 on 2023-06-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_remove_adminlogin_id_alter_adminlogin_pid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adminlogin", old_name="pid", new_name="aid",
        ),
    ]
