# Generated by Django 4.2.1 on 2023-06-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0025_rename_pid_adminlogin_aid"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tid", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="selection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub1", models.CharField(max_length=10)),
                ("sub2", models.CharField(max_length=10)),
                ("sub3", models.CharField(max_length=10)),
                ("sub4", models.CharField(max_length=10)),
                ("count", models.IntegerField()),
                (
                    "tid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.teacher"
                    ),
                ),
            ],
        ),
    ]
