# Generated by Django 4.2.1 on 2023-06-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0027_rename_selection_teacherselection"),
    ]

    operations = [
        migrations.CreateModel(
            name="classDivisions",
            fields=[
                (
                    "classname",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("alloc", models.CharField(max_length=10)),
                ("exp", models.IntegerField()),
                (
                    "depid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.department",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.subject"
                    ),
                ),
            ],
        ),
    ]
