# Generated by Django 4.2.2 on 2023-06-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_department_division_subject_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherselection',
            name='id',
        ),
        migrations.AddField(
            model_name='teacherselection',
            name='selectionid',
            field=models.CharField(default='S0001', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
