# Generated by Django 4.2.2 on 2023-06-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_teacherselection_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classdivisions',
            old_name='alloc',
            new_name='classalloc',
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('alloc', models.IntegerField(default=0)),
                ('status', models.CharField(default='ON', max_length=20)),
                ('sub1', models.CharField(default=None, max_length=20)),
                ('sub2', models.CharField(default=None, max_length=20)),
                ('lab1', models.CharField(default=None, max_length=20)),
                ('lab2', models.CharField(default=None, max_length=20)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher')),
            ],
        ),
    ]
