# Generated by Django 4.2.2 on 2023-06-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_rename_alloc_classdivisions_classalloc_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='exp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
