# Generated by Django 4.2.2 on 2023-06-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_phaseno_phase_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='mail',
            field=models.CharField(default='val@gmail.com', max_length=20),
            preserve_default=False,
        ),
    ]
