# Generated by Django 4.2.2 on 2023-06-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_phase_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaseno',
            name='active',
            field=models.CharField(default='phase1', max_length=20),
            preserve_default=False,
        ),
    ]
