# Generated by Django 4.2.2 on 2023-06-28 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_classdivisions_sem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='classDivisions',
        ),
    ]
