# Generated by Django 4.2.2 on 2023-06-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_classdivisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdivisions',
            name='subtype',
            field=models.CharField(default='L', max_length=20),
            preserve_default=False,
        ),
    ]
