# Generated by Django 4.2.2 on 2023-06-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_classdivisions_subtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassDivisions',
        ),
    ]
