# Generated by Django 4.2.2 on 2023-06-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_classdivisions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phase',
        ),
    ]
