# Generated by Django 4.2.2 on 2023-06-30 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_delete_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('alloc', models.IntegerField(default=0)),
                ('status', models.CharField(default='ON', max_length=20)),
                ('exp', models.IntegerField()),
                ('sub1', models.CharField(max_length=20)),
                ('sub2', models.CharField(max_length=20)),
                ('sub3', models.CharField(max_length=20)),
                ('sub4', models.CharField(max_length=20)),
                ('sub5', models.CharField(max_length=20)),
                ('sub6', models.CharField(max_length=20)),
                ('academicyear', models.CharField(default='2023', max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher')),
            ],
        ),
    ]
