# Generated by Django 4.2.2 on 2023-06-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_phase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phase',
        ),
    ]
