# Generated by Django 4.2.2 on 2023-06-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subname',
            field=models.CharField(max_length=45),
        ),
    ]
