# Generated by Django 4.2.2 on 2023-07-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_alter_subject_subname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherSelection',
        ),
    ]
