# Generated by Django 4.2.2 on 2023-07-06 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherSubject',
            fields=[
                ('subid', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('subname', models.CharField(max_length=45)),
                ('sem', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('subtype', models.CharField(default='T', max_length=5)),
                ('count', models.IntegerField()),
                ('depid', models.ForeignKey(default='D0001', on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
        ),
    ]
