# Generated by Django 4.2.2 on 2023-07-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_othersubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='clash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clashid', models.CharField(max_length=20)),
            ],
        ),
    ]
