# Generated by Django 4.2.2 on 2023-07-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_clash'),
    ]

    operations = [
        migrations.CreateModel(
            name='semtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=20)),
            ],
        ),
    ]
