# Generated by Django 4.2.2 on 2023-07-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_semtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='phaseget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vla', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Phaseteacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('sub1', models.CharField(max_length=20)),
                ('sub2', models.CharField(max_length=20)),
                ('sub3', models.CharField(max_length=20)),
                ('sub4', models.CharField(max_length=20)),
                ('sub5', models.CharField(max_length=20)),
                ('sub6', models.CharField(max_length=20)),
            ],
        ),
    ]
