# Generated by Django 4.2.2 on 2023-07-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_phaseget_phaseteacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phaseget',
            old_name='vla',
            new_name='val',
        ),
    ]
