# Generated by Django 4.2.2 on 2023-07-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_rename_vla_phaseget_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaseteacher',
            name='classname1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='phaseteacher',
            name='classname2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='phaseteacher',
            name='classname3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='phaseteacher',
            name='classname4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='phaseteacher',
            name='classname5',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='phaseteacher',
            name='classname6',
            field=models.CharField(default='', max_length=20),
        ),
    ]
