# Generated by Django 4.2.2 on 2023-07-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_phaseteacher_classname1_phaseteacher_classname2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaseteacher',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
