# Generated by Django 4.2.2 on 2023-07-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_phaseteacher_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phaseteacher',
            name='no',
        ),
    ]
