# Generated by Django 4.2.2 on 2023-07-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_remove_phaseteacher_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherselection',
            name='sub3',
        ),
        migrations.RemoveField(
            model_name='teacherselection',
            name='sub4',
        ),
        migrations.RemoveField(
            model_name='teacherselection',
            name='sub5',
        ),
        migrations.RemoveField(
            model_name='teacherselection',
            name='sub6',
        ),
    ]
