# Generated by Django 4.2.2 on 2023-07-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_remove_teacherselection_sub3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='resolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField()),
            ],
        ),
    ]
